building: #自己随便命名的
  image: node:latest #node镜像为最新版的，最好指定版本号
  stage: build #当前stage阶段为build
  script: #build阶段运行的脚本
    - yarn #根据package.json来安装依赖 progress设为false是为了不打印安装的具体进度，no optional是为了跳过npm推荐的但不是编译必须的，也没有写在package.json里一些依赖，比如说查看源代码等
    - yarn build #打包
  artifacts: #工件，可以缓存在gitlab的流水线记录中，供直接下载
    expire_in: 3 days #工件缓存的有效时间
    paths: #路径
      - novels/.vuepress/dist #工件指向的目录，这里指整个dist目录

cache: #缓存
  paths: #路径
    - node_modules/ #缓存node_mudules将大大提高ci运行的速度

pages: #随便起的名字
  stage: deploy #当前阶段为deploy
  script: #deploy阶段运行的命令
    - rm -rf public/* #linux命令，递归无询问删除public目录下所有文件- mv dist/* public #将dist目录下的所有文件都移动到public目录下
  artifacts: #工件缓存
    expire_in: 3 days #时效为3天
    paths: #路径
      - public #缓存整个public目录的文件
  only:
    - master #ceate pages下的所有操作只在dev分支上进行
