version: '3.5'

services:
  yy-novels_build:
    build: ./
    container_name: 'yy-novels'
    volumes:
      - dist:/usr/src/app/novels/.vuepress/dist

  yy-novels_web:
    image: nginx
    ports:
      - 80:80
    container_name: 'yy-novels_web'
    restart: unless-stopped
    volumes:
      - dist:/usr/share/nginx/html/yy-novels/:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf/

volumes:
  dist:
